package edu.ucr.rp.algoritmos.proyecto.gui.scenes.managepane.model;

public enum PaneName {
   ADD_USER_FROM_SUPERADMIN,GRAPHIC,CHANGEP,ADD_ADMIN, BASE, LOG_IN, MAIN_PANE, CHANGE_PASSWORD, GENERATE_REPORT, PERSONAL_PROGRESS, ADD_USER_FORM, MODIFY_USER_FORM, VIEW_USER_FORM, ADD_DATE_FORM, MODIFY_DATE_FORM, VIEW_DATES
}
