package edu.ucr.rp.algoritmos.proyecto.gui.scenes.managepane.model;

public enum PaneName {

    BASE, LOG_IN, MAIN_PANE, SIGN_UP_FORM, CHANGE_PASSWORD, GENERATE_REPORT, PERSONAL_PROGRESS, ADD_CUSTOMER_FORM, MODIFY_USER_FORM, VIEW_ADMIN_FORM, ADD_DATE_FORM, MODIFY_DATE_FORM, VIEW_DATES,ADD_ANNOTATION_FORM, ADD_ADMIN,  GRAPHIC,VIEW_CUSTOMER_FORM

}
